env: "local"
grpc_server:
  host: "localhost"
  port: "50067"
arbitrage_db:
  dsn: "host=localhost user=postgres password=admin dbname=shvark_arbitrage_bot_service port=5432 sslmode=disable"
log_config:
  log_level: "debug"
  log_format: "json"
  log_output: "stdout"